---
- name: Add FR locale
  become: yes
  locale_gen: name="fr_FR.UTF-8" state=present

- name: Rm EN locale
  become: yes
  locale_gen: name="en_GB.UTF-8" state=absent

- name: Set locale
  become: yes
  template: src=locale.j2 dest=/etc/default/locale force=yes

- name: Keyboard
  become: yes
  template: src=keyboard.j2 dest=/etc/default/keyboard force=yes
  notify:
    - Reboot
    - Wait for server to restart
...