---
- name: Reboot
  become: yes
  shell: sleep 2 && shutdown -r now "Ansible reboot"
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for server to restart
  local_action: wait_for
  become: false
  args:
    host: "{{ ansible_ssh_host }}"
    port: 22
    state: started
    delay: 30
    timeout: 300

...