---
- name: Reboot
  become: yes
  raw: reboot
  async: 0
  poll: 0
  ignore_errors: true

- name: Wait for server to restart
  local_action: wait_for host="{{ ansible_ssh_host }}" port=22 delay=1 timeout=300

...